export const FETCH_ALL_LOCATION_REQUEST = "FETCH_ALL_LOCATION_REQUEST";
export const FETCH_ALL_LOCATION_SUCCESS = "FETCH_ALL_LOCATION_SUCCESS";
export const FETCH_ALL_LOCATION_ERROR = "FETCH_ALL_LOCATION_ERROR";
