// import "react-alice-carousel/lib/scss/alice-carousel.scss";
import styles from "../styles/Home.module.scss";
import "react-alice-carousel/lib/alice-carousel.css";
import Head from "next/head";

import SicilyLogo from "../components/SicilyImg";
import Carousel from "../components/Carousel";
import LogoCitta from "../components/Cards/CardLogoCitta";
import Map from "../components/BoxMap";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gira, vota e furria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://api.tiles.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.css"
        />
      </Head>

      <main>
        <div className={styles.titleContain}>
          <h1 className={styles.title}>Gira, vota e furria</h1>
          <div className={styles.logoTitle}>
            <img
              src={
                "https://m.media-amazon.com/images/I/91fCK5XIrqL._AC_UL320_.jpg"
              }
            />
          </div>
        </div>

        <section className={styles.componentWrapper}>
          <SicilyLogo />
        </section>

        <section className={styles.componentWrapper}>
          <Carousel />
        </section>

        <section className={styles.componentWrapper}>
          <LogoCitta />
        </section>

        <section className={styles.componentWrapper}>
          <Map lng={14.262851} lat={37.5099321} zoom={6.6} />
        </section>
      </main>
    </div>
  );
}
